Repository Khan/wonder-blocks, pull requests merged in 2025-05, with the labels that each got.

#2577 Try to fix the Storybook Test addon
  .changeset/big-masks-applaud.md
  __docs__/_overview_.mdx
  __docs__/components/gallery/component-gallery.tsx
  __docs__/wonder-blocks-button/button.stories.tsx
  __docs__/wonder-blocks-cell/detail-cell.stories.tsx
  __docs__/wonder-blocks-pill/pill-variants.stories.tsx
  __docs__/wonder-blocks-styles/focus-styles.stories.tsx
  vitest.config.ts
Labels: audit, olc-5.0.65aec

#2579 [WB-1899.1] Migrate Button - All Variants story to use StateSheet
  .changeset/thick-pigs-agree.md
  .storybook/modes.ts
  __docs__/wonder-blocks-button/button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/button-variants.stories.tsx
Labels: olc-5.0.65aec

#2576 Make sure that the tooltip bubble is using the same ID as the aria-describedby attribute on the anchor
  .changeset/moody-stingrays-jog.md
  packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-anchor.test.tsx
  packages/wonder-blocks-tooltip/src/components/__tests__/tooltip.test.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip-anchor.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip.tsx
Labels: olc-5.0.65aec

#2584 [🔥AUDIT🔥] [WB-1936] Disable Storybook tests check
  .changeset/neat-keys-perform.md
  .github/workflows/chromatic-build.yml
Labels: audit, olc-5.0.65aec

#2575 [WB-1931] Link: Add `viewTransition` prop to enable the View Transitions API
  .changeset/six-maps-tap.md
  __docs__/wonder-blocks-link/link.stories.tsx
  package.json
  packages/wonder-blocks-clickable/src/components/__tests__/clickable-behavior.test.tsx
  packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-link/src/components/link.tsx
  patches/react-router-dom-v5-compat@6.30.0.patch
  pnpm-lock.yaml
  static/sb-styles/preview.css
Labels: olc-5.0.65aec

#2583 [WB-1895] Add semanticColor.input category
  .changeset/fresh-birds-march.md
  .changeset/quick-tables-rule.md
  __docs__/foundations-color.mdx
  packages/wonder-blocks-dropdown/src/components/checkbox.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.65aec

#2586 [WB-1895.2] Tokens: Use transparent background for secondary.disabled state
  .changeset/itchy-fans-look.md
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.65aec

#2588 [WB-1937] IconButton not opening with the `Space` key (fix)
  .changeset/sweet-pianos-end.md
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-icon/phosphor-icon.argtypes.ts
  packages/wonder-blocks-dropdown/src/components/__tests__/action-menu.test.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button.tsx
Labels: olc-5.0.65aec

#2581 [WB-1899.3] Simplify Button theme and styles
  .changeset/heavy-carpets-flow.md
  .changeset/silly-hats-hunt.md
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  packages/wonder-blocks-button/package.json
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-button/src/themes/khanmigo.ts
  packages/wonder-blocks-button/tsconfig-build.json
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  pnpm-lock.yaml
Labels: olc-5.0.65aec

#2585 Tabs: Fix keyboard navigation for right-to-left
  .changeset/late-carpets-jam.md
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
Labels: olc-5.0.65aec

#2574 Fix tooltip and popover bugs found when integrating with tabs
  .changeset/gold-pigs-applaud.md
  .changeset/metal-kiwis-smell.md
  __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-playtesting.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-utils.tsx
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-popover/src/components/__tests__/initial-focus.test.tsx
  packages/wonder-blocks-popover/src/components/focus-manager.tsx
  packages/wonder-blocks-popover/src/components/initial-focus.ts
  packages/wonder-blocks-popover/src/components/popover.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
Labels: olc-5.0.407da

#2593 This is a feature-branch pull-request from `feature/tabs` to `main`
  .changeset/breezy-bulldogs-yawn.md
  .changeset/dirty-pens-share.md
  .changeset/eighty-rockets-repeat.md
  .changeset/fair-ants-hunt.md
  .changeset/gold-pigs-applaud.md
  .changeset/late-carpets-jam.md
  .changeset/little-laws-flash.md
  .changeset/loud-lamps-deny.md
  .changeset/metal-kiwis-smell.md
  .changeset/new-swans-hug.md
  .changeset/polite-spies-press.md
  .changeset/twelve-pillows-lay.md
  .changeset/twenty-pans-film.md
  __docs__/components/all-variants.tsx
  __docs__/components/placeholder.tsx
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-utils.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-tabs/tab-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-playtesting.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-utils.tsx
  __docs__/wonder-blocks-tabs/tabs.accessibility.mdx
  __docs__/wonder-blocks-tabs/tabs.argtypes.ts
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-core/src/util/__tests__/focus.test.tsx
  packages/wonder-blocks-core/src/util/focus.ts
  packages/wonder-blocks-core/src/util/keys.ts
  packages/wonder-blocks-popover/src/components/__tests__/initial-focus.test.tsx
  packages/wonder-blocks-popover/src/components/focus-manager.tsx
  packages/wonder-blocks-popover/src/components/initial-focus.ts
  packages/wonder-blocks-popover/src/components/popover.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tab-panel.test.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tablist.test.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
  packages/wonder-blocks-tabs/src/components/tab-panel.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
  packages/wonder-blocks-tabs/src/components/tablist.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
  packages/wonder-blocks-tabs/src/hooks/use-tab-indicator.ts
  packages/wonder-blocks-tabs/src/index.ts
  packages/wonder-blocks-tabs/tsconfig-build.json
Labels: integration-branch, feature-branch, olc-5.0.65aec

#2589 [WB-1899.4] Button: Add neutral actionType
  .changeset/sharp-avocados-explode.md
  .changeset/spicy-kiwis-scream.md
  __docs__/wonder-blocks-button/button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/button.stories.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.65aec

#2590 [WB-1899.5] Refactor `ButtonCore` to make it an unstyled component
  .changeset/twelve-paws-kneel.md
  __docs__/wonder-blocks-button/button.stories.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/components/button-unstyled.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/index.ts
  packages/wonder-blocks-button/src/util/button.types.ts
Labels: olc-5.0.65aec

#2595 Set up badge package
  .changeset/seven-peaches-look.md
  __docs__/wonder-blocks-badge/badge.stories.tsx
  packages/wonder-blocks-badge/.npmignore
  packages/wonder-blocks-badge/package.json
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/src/index.ts
  packages/wonder-blocks-badge/tsconfig-build.json
  packages/wonder-blocks-badge/types
  pnpm-lock.yaml
Labels: olc-5.0.65aec

#2578 This is a feature-branch pull-request from `feature/button-refactor` to `main`
  .changeset/eighty-turtles-count.md
  .changeset/fresh-birds-march.md
  .changeset/heavy-carpets-flow.md
  .changeset/itchy-fans-look.md
  .changeset/quick-tables-rule.md
  .changeset/sharp-avocados-explode.md
  .changeset/silly-hats-hunt.md
  .changeset/spicy-kiwis-scream.md
  .changeset/thick-pigs-agree.md
  .changeset/twelve-paws-kneel.md
  .storybook/modes.ts
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-button/button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/button-variants.stories.tsx
  __docs__/wonder-blocks-button/button.stories.tsx
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-layout/spring.stories.tsx
  __docs__/wonder-blocks-layout/strut.stories.tsx
  __docs__/wonder-blocks-popover/popover.stories.tsx
  packages/wonder-blocks-button/package.json
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/components/button-unstyled.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/index.ts
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-button/src/themes/khanmigo.ts
  packages/wonder-blocks-button/src/util/button.types.ts
  packages/wonder-blocks-button/tsconfig-build.json
  packages/wonder-blocks-dropdown/src/components/checkbox.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  pnpm-lock.yaml
Labels: integration-branch, feature-branch, olc-5.0.65aec

#2562 [WB-1896] Tokens: Add `thunderblocks` theme to Wonder Blocks
  .changeset/flat-tables-grin.md
  .storybook/preview.tsx
  __docs__/wonder-blocks-icon-button/icon-button-testing-snapshots.stories.tsx
  package.json
  packages/wonder-blocks-theming/src/types.ts
  packages/wonder-blocks-tokens/src/theme/semantic/internal/primitive-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/thunderblocks.ts
  pnpm-lock.yaml
Labels: olc-5.0.fb2b9

#2599 [WB-1942] Adapt CSS build tools to export CSS vars from multiple packages
  .changeset/chatty-worms-push.md
  .changeset/pink-cooks-kneel.md
  .changeset/sixty-kids-clean.md
  .changeset/weak-snakes-give.md
  .gitignore
  build-settings/build-css.ts
  package.json
  packages/wonder-blocks-dropdown/package.json
  packages/wonder-blocks-icon-button/package.json
  packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button.tsx
  packages/wonder-blocks-icon-button/src/theme/default.ts
  packages/wonder-blocks-icon-button/src/theme/index.ts
  packages/wonder-blocks-icon-button/src/theme/thunderblocks.ts
  packages/wonder-blocks-icon-button/src/themes/themed-icon-button.tsx
  packages/wonder-blocks-tokens/bin/cli.js
  packages/wonder-blocks-tokens/package.json
  packages/wonder-blocks-tokens/src/build/generate-css-variables.ts
  packages/wonder-blocks-tokens/src/index.ts
  packages/wonder-blocks-tokens/src/internal/__test__/generate-tokens.test.ts
  packages/wonder-blocks-tokens/src/internal/__test__/map-values-to-css-vars.test.ts
  packages/wonder-blocks-tokens/src/internal/generate-tokens.ts
  pnpm-lock.yaml
  turbo.json
Labels: olc-5.0.37c28

#2604 Export ActionTrigger type for Banner
  .changeset/mighty-chairs-roll.md
  packages/wonder-blocks-banner/src/components/banner.tsx
Labels: olc-5.0.f1826

#2603 Chromatic: Migrate All Variants stories to use StateSheet
  .changeset/clever-feet-appear.md
  .storybook/modes.ts
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-dropdown/action-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select-variants.stories.tsx
  __docs__/wonder-blocks-dropdown/option-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select-variants.stories.tsx
  __docs__/wonder-blocks-form/checkbox-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/radio-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-link/link-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-link/link-variants.stories.tsx
  __docs__/wonder-blocks-pill/pill-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-pill/pill-variants.stories.tsx
Labels: olc-5.0.37c28

#2605 [WB-1860.1] Refactor `IconButton` to support unstyled and styled buttons
  .changeset/hip-knives-own.md
  packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button-unstyled.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button.tsx
  packages/wonder-blocks-icon-button/src/util/icon-button-util.ts
  packages/wonder-blocks-icon-button/src/util/icon-button.types.ts
Labels: olc-5.0.3d2dc

#2606 [WB-1860.2] Add `thunderblocks` theme to IconButton
  .changeset/funny-toys-leave.md
  .changeset/itchy-worms-wonder.md
  packages/wonder-blocks-icon-button/src/components/icon-button.tsx
  packages/wonder-blocks-icon-button/src/theme/default.ts
  packages/wonder-blocks-icon-button/src/theme/thunderblocks.ts
  packages/wonder-blocks-icon-button/src/util/icon-button-util.test.ts
  packages/wonder-blocks-icon-button/src/util/icon-button-util.ts
  packages/wonder-blocks-tokens/src/theme/primitive/sizing.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
Labels: olc-5.0.3d2dc

#2601 Add `StatusBadge` component
  .changeset/early-worms-relate.md
  __docs__/wonder-blocks-badge/_overview_.mdx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
  packages/wonder-blocks-badge/src/components/__tests__/status-badge.test.tsx
  packages/wonder-blocks-badge/src/components/status-badge.tsx
  packages/wonder-blocks-badge/src/index.ts
Labels: olc-5.0.3d2dc

#2614 Bump TypeScript target to ES2021
  .changeset/famous-hotels-fly.md
  build-settings/rollup.config.mjs
  tsconfig-common.json
Labels: olc-5.0.57876

#2610 Adds `Icon` component to support custom icons.
  .changeset/great-walls-pay.md
  .changeset/pink-needles-rhyme.md
  __docs__/components/single-colored-icon.svg
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.argtypes.ts
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  __docs__/wonder-blocks-icon/icon.stories.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/src/components/status-badge.tsx
  packages/wonder-blocks-icon/package.json
  packages/wonder-blocks-icon/src/components/__tests__/icon.test.tsx
  packages/wonder-blocks-icon/src/components/icon.tsx
  packages/wonder-blocks-icon/src/index.ts
  packages/wonder-blocks-icon/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.3d2dc

#2613 [WB-1941.1] Add `core.border` semantic color tokens
  .changeset/nice-tools-shake.md
  .changeset/perfect-fishes-pump.md
  __docs__/components/all-variants.tsx
  __docs__/components/color.tsx
  __docs__/components/placeholder.tsx
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-cell/detail-cell.stories.tsx
  __docs__/wonder-blocks-clickable/clickable.stories.tsx
  __docs__/wonder-blocks-dropdown/listbox.stories.tsx
  __docs__/wonder-blocks-form/checkbox-group.stories.tsx
  __docs__/wonder-blocks-form/radio-group.stories.tsx
  __docs__/wonder-blocks-link/link.stories.tsx
  __docs__/wonder-blocks-pill/pill.stories.tsx
  __docs__/wonder-blocks-popover/popover.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-tokens/tokens-semantic-color.mdx
  package.json
  packages/wonder-blocks-accordion/src/components/accordion-section.tsx
  packages/wonder-blocks-clickable/src/components/clickable.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
  packages/wonder-blocks-dropdown/src/components/separator-item.tsx
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-modal/src/themes/default.ts
  packages/wonder-blocks-pill/src/components/pill.tsx
  packages/wonder-blocks-popover/src/components/popover-content-core.tsx
  packages/wonder-blocks-styles/src/styles/action-styles.ts
  packages/wonder-blocks-tabs/src/components/tablist.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-tokens/src/tokens/color.ts
  packages/wonder-blocks-toolbar/src/components/toolbar.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
Labels: olc-5.0.3d2dc

#2617 [WB-1941.2] Add core.background and core.foreground semantic color tokens
  .changeset/kind-cherries-report.md
  .changeset/pink-pandas-tap.md
  .storybook/preview.tsx
  __docs__/foundations-color.mdx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-pill/src/components/pill.tsx
  packages/wonder-blocks-switch/src/themes/default.ts
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.3d2dc

#2618 [WB-1862] Add theming support to Link
  .changeset/nine-cougars-enjoy.md
  .changeset/rotten-singers-check.md
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.3d2dc

#2616 Add GemBadge and GemIcon components
  .changeset/khaki-actors-bow.md
  .changeset/serious-jeans-thank.md
  __docs__/wonder-blocks-badge/_overview_.mdx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.argtypes.ts
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/gem-badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  __docs__/wonder-blocks-icon/custom-icon-components.stories.tsx
  __docs__/wonder-blocks-icon/icon.stories.tsx
  packages/wonder-blocks-badge/package.json
  packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
  packages/wonder-blocks-badge/src/components/__tests__/gem-badge.test.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/src/components/gem-badge.tsx
  packages/wonder-blocks-badge/src/components/status-badge.tsx
  packages/wonder-blocks-badge/src/index.ts
  packages/wonder-blocks-badge/src/types.ts
  packages/wonder-blocks-badge/tsconfig-build.json
  packages/wonder-blocks-icon/src/components/__tests__/custom-icon-components.test.tsx
  packages/wonder-blocks-icon/src/components/custom-icon-components/gem-icon.tsx
  packages/wonder-blocks-icon/src/hooks/__tests__/use-svg-attributes.test.ts
  packages/wonder-blocks-icon/src/hooks/use-svg-attributes.ts
  packages/wonder-blocks-icon/src/index.ts
  packages/wonder-blocks-icon/src/types.ts
  pnpm-lock.yaml
Labels: olc-5.0.3d2dc

#2624 [WB-1915.0] Reorganize IconButton to prepare for Chonky/ActivityIconButton
  .changeset/dull-dingos-itch.md
  __docs__/wonder-blocks-icon-button/_overview_.mdx
  __docs__/wonder-blocks-icon-button/icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/icon-button.stories.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button-types.test.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button-unstyled.test.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button.test.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button-unstyled.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button.tsx
  packages/wonder-blocks-icon-button/src/util/icon-button.types.ts
Labels: olc-5.0.5070e

#2627 [WB-1859.2] Reorganize Button to prepare for TB theme + ActivityButton
  .changeset/quiet-poems-wave.md
  __docs__/wonder-blocks-button/_overview_.mdx
  __docs__/wonder-blocks-button/accessibility.stories.tsx
  __docs__/wonder-blocks-button/best-practices.stories.tsx
  __docs__/wonder-blocks-button/button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/button.stories.tsx
  __docs__/wonder-blocks-button/navigation-callbacks.stories.tsx
  packages/wonder-blocks-button/src/components/__tests__/button-types.test.tsx
  packages/wonder-blocks-button/src/components/__tests__/button-unstyled.test.tsx
  packages/wonder-blocks-button/src/components/__tests__/button.test.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/util/button.types.ts
Labels: olc-5.0.9bb25

#2626 Supporting Badge with Tooltip
  .changeset/cold-apes-yawn.md
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  packages/wonder-blocks-badge/package.json
  packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.9bb25
