Repository Khan/wonder-blocks, pull requests merged in 2025-07, with the labels that each got.

#2703 Change core background success strong to green 20
  .changeset/metal-pans-call.md
  .changeset/popular-bats-fly.md
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
Labels: olc-5.0.d08c8

#2705 Add `overdue` kind for `DueBadge` and include icons
  .changeset/neat-news-chew.md
  __docs__/wonder-blocks-badge/_overview_.mdx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.argtypes.ts
  __docs__/wonder-blocks-badge/due-badge.stories.tsx
  packages/wonder-blocks-badge/package.json
  packages/wonder-blocks-badge/src/components/__tests__/badge.typestest.tsx
  packages/wonder-blocks-badge/src/components/__tests__/due-badge.test.tsx
  packages/wonder-blocks-badge/src/components/due-badge.tsx
  pnpm-lock.yaml
Labels: olc-5.0.d08c8

#2697 Add shared feedback tokens to semanticColor
  .changeset/small-cats-kick.md
  __docs__/foundations-color.mdx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.bfebe

#2715 LabeledField: Remove `required` prop
  .changeset/fifty-bananas-explode.md
  .changeset/strange-squids-try.md
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  __docs__/wonder-blocks-form/labeled-text-field.stories.tsx
  __docs__/wonder-blocks-form/text-area.stories.tsx
  __docs__/wonder-blocks-form/text-field.stories.tsx
  __docs__/wonder-blocks-labeled-field/accessibility.mdx
  __docs__/wonder-blocks-labeled-field/labeled-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field.argtypes.ts
  __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
  __docs__/wonder-blocks-search-field/search-field.stories.tsx
  packages/wonder-blocks-labeled-field/src/components/__tests__/labeled-field.test.tsx
  packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
  packages/wonder-blocks-labeled-field/src/theme/default.ts
  packages/wonder-blocks-labeled-field/src/theme/thunderblocks.ts
Labels: olc-5.0.d08c8

#2720 Do not try to focus hidden elements in `FocusTrap`
  .changeset/flat-rivers-reflect.md
  packages/wonder-blocks-modal/src/components/__tests__/focus-trap.test.tsx
  packages/wonder-blocks-modal/src/components/focus-trap.tsx
Labels: olc-5.0.6d36a

#2718 [WB-2002] Remove deprecated theming APIs and docs + khanmigo theme
  .changeset/flat-peaches-notice.md
  .storybook/modes.ts
  .storybook/preview.tsx
  __docs__/wonder-blocks-theming/adding-a-theme.mdx
  __docs__/wonder-blocks-theming/create-theme-context.mdx
  __docs__/wonder-blocks-theming/merge-theme.mdx
  __docs__/wonder-blocks-theming/theme-examples.tsx
  __docs__/wonder-blocks-theming/theme-switcher-context.mdx
  __docs__/wonder-blocks-theming/theme-switcher.stories.tsx
  __docs__/wonder-blocks-theming/use-scoped-theme.mdx
  __docs__/wonder-blocks-theming/use-styles.mdx
  __docs__/wonder-blocks-theming/with-scoped-theme.mdx
  packages/wonder-blocks-theming/src/components/__tests__/with-scoped-theme.test.tsx
  packages/wonder-blocks-theming/src/components/with-scoped-theme.tsx
  packages/wonder-blocks-theming/src/hooks/__tests__/use-scoped-theme.test.tsx
  packages/wonder-blocks-theming/src/hooks/__tests__/use-styles.test.ts
  packages/wonder-blocks-theming/src/hooks/use-scoped-theme.ts
  packages/wonder-blocks-theming/src/hooks/use-styles.ts
  packages/wonder-blocks-theming/src/index.ts
  packages/wonder-blocks-theming/src/types.ts
  packages/wonder-blocks-theming/src/utils/__tests__/create-theme-context.test.tsx
  packages/wonder-blocks-theming/src/utils/__tests__/theme-switcher-context.test.tsx
  packages/wonder-blocks-theming/src/utils/create-theme-context.ts
Labels: olc-5.0.6d36a

#2722 [WB-2042.2] Remove semanticColor.text category
  .changeset/clever-humans-know.md
  .changeset/fresh-snakes-smoke.md
  .changeset/friendly-buses-fly.md
  .changeset/thick-coins-chew.md
  __docs__/components/color.tsx
  __docs__/components/state-sheet.tsx
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-clickable/clickable.stories.tsx
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  __docs__/wonder-blocks-form/checkbox-group.stories.tsx
  __docs__/wonder-blocks-form/text-area.stories.tsx
  __docs__/wonder-blocks-form/text-field.stories.tsx
  __docs__/wonder-blocks-link/link.stories.tsx
  __docs__/wonder-blocks-pill/pill.stories.tsx
  __docs__/wonder-blocks-popover/popover-content-core.stories.tsx
  __docs__/wonder-blocks-styles/focus-styles.stories.tsx
  __docs__/wonder-blocks-tokens/tokens-semantic-color.mdx
  __docs__/wonder-blocks-tooltip/tooltip.stories.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-form/src/components/choice-internal.tsx
  packages/wonder-blocks-form/src/components/field-heading.tsx
  packages/wonder-blocks-form/src/components/group-styles.ts
  packages/wonder-blocks-form/src/theme/default.ts
  packages/wonder-blocks-form/src/theme/thunderblocks.ts
  packages/wonder-blocks-styles/src/styles/action-styles.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-toolbar/src/components/toolbar.tsx
Labels: olc-5.0.6d36a

#2731 Fix TB css variable values in color foundation docs
  .changeset/swift-tigers-look.md
  .storybook/preview.tsx
  __docs__/components/color.tsx
  __docs__/components/tokens-util.ts
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-tokens/semantic-color-groups.stories.tsx
Labels: olc-5.0.6d36a

#2737 ButtonCore: Fix passing in invalid attributes
  .changeset/healthy-crabs-refuse.md
  packages/wonder-blocks-button/src/components/button-core.tsx
Labels: olc-5.0.6d36a
