Repository Khan/wonder-blocks, pull requests merged in 2025-09, with the labels that each got.

#2773 DrawerDialog: Add support for zeroed out padding
  .changeset/thin-candles-nail.md
  __docs__/wonder-blocks-modal/drawer-dialog.argtypes.ts
  __docs__/wonder-blocks-modal/drawer-dialog.stories.tsx
  __docs__/wonder-blocks-modal/drawer-launcher-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-modal/drawer-launcher.stories.tsx
  __docs__/wonder-blocks-modal/flexible-dialog.argtypes.ts
  __docs__/wonder-blocks-modal/flexible-dialog.stories.tsx
  packages/wonder-blocks-modal/src/components/drawer-dialog.tsx
  packages/wonder-blocks-modal/src/components/flexible-dialog.tsx
  packages/wonder-blocks-modal/src/components/flexible-panel.tsx
  packages/wonder-blocks-modal/src/components/modal-content.tsx
Labels: olc-5.0.e7698

#2774 Button and ActivityButton: Support custom icons
  .changeset/smart-ants-clap.md
  __docs__/wonder-blocks-button/activity-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/activity-button.stories.tsx
  __docs__/wonder-blocks-button/button-shared.argtypes.ts
  __docs__/wonder-blocks-button/button.stories.tsx
  packages/wonder-blocks-button/src/components/__tests__/activity-button.test.tsx
  packages/wonder-blocks-button/src/components/__tests__/button-with-icon.test.tsx
  packages/wonder-blocks-button/src/components/activity-button.tsx
  packages/wonder-blocks-button/src/components/button-icon.tsx
  packages/wonder-blocks-button/src/util/button.types.ts
Labels: olc-5.0.e7698

#2781 Banner: Support custom icons
  .changeset/wicked-rabbits-buy.md
  __docs__/wonder-blocks-banner/banner-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-banner/banner.stories.tsx
  packages/wonder-blocks-banner/src/components/banner.tsx
Labels: olc-5.0.5f719

#2778 [WB-2059] Sync shadow color tokens with Figma tokens
  .changeset/chilly-rockets-know.md
  .changeset/mighty-countries-vanish.md
  .changeset/ninety-poets-rest.md
  packages/wonder-blocks-dropdown/src/theme/default.ts
  packages/wonder-blocks-dropdown/src/theme/thunderblocks.ts
  packages/wonder-blocks-modal/src/theme/thunderblocks.ts
  packages/wonder-blocks-popover/src/components/popover-content-core.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-tooltip/src/components/__tests__/tooltip-tail.test.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip-tail.tsx
Labels: olc-5.0.6d36a

#2780 Update docs to provide clearer details on fetch policy behaviors
  .changeset/chatty-squids-buy.md
  __docs__/wonder-blocks-data/exports.use-cached-effect.mdx
  __docs__/wonder-blocks-data/types.fetch-policy.mdx
  packages/wonder-blocks-data/src/hooks/use-cached-effect.ts
  packages/wonder-blocks-data/src/util/types.ts
Labels: olc-5.0.e6bd8

#2787 Fix Storybook docs from rendering in rtl unexpectedly
  .changeset/flat-dolls-clean.md
  .storybook/preview.tsx
Labels: olc-5.0.5f719

#2786 Allow ActionMenu to support any valid popper placement
  .changeset/hungry-carrots-leave.md
  __docs__/wonder-blocks-dropdown/action-menu.argtypes.ts
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  packages/wonder-blocks-dropdown/src/components/action-menu.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-popper.tsx
Labels: olc-5.0.0b737

#2794 Tabs: Set type on tabs to prevent form submission
  .changeset/rare-cheetahs-scream.md
  packages/wonder-blocks-tabs/src/components/__tests__/tab.test.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
Labels: olc-5.0.0b737
