Repository Khan/wonder-blocks, pull requests merged in 2025-06, with the labels that each got.

#2619 [WB-1915.1]: Add Chonky (ActivityIconbutton) component
  .changeset/honest-mice-leave.md
  __docs__/wonder-blocks-icon-button/_overview_.mdx
  __docs__/wonder-blocks-icon-button/activity-icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/activity-icon-button.stories.tsx
  __docs__/wonder-blocks-icon-button/icon-button-shared.argtypes.ts
  __docs__/wonder-blocks-icon-button/icon-button.argtypes.ts
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button-types.test.tsx
  packages/wonder-blocks-icon-button/src/components/activity-icon-button.tsx
  packages/wonder-blocks-icon-button/src/index.ts
  packages/wonder-blocks-icon-button/src/util/icon-button.types.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.3d2dc

#2632 [WB-1915.2] ActivityIconbutton: Add `label` prop
  .changeset/nasty-impalas-sparkle.md
  __docs__/wonder-blocks-icon-button/activity-icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/activity-icon-button.stories.tsx
  packages/wonder-blocks-icon-button/package.json
  packages/wonder-blocks-icon-button/src/components/__tests__/activity-icon-button.test.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/activity-icon-button.typestest.tsx
  packages/wonder-blocks-icon-button/src/components/__tests__/icon-button-types.test.tsx
  packages/wonder-blocks-icon-button/src/components/activity-icon-button.tsx
  packages/wonder-blocks-icon-button/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.9bb25

#2631 Set up tokens for gems, streak, due, and feedback for Badge components
  .changeset/curly-files-rush.md
  .changeset/eighty-ties-crash.md
  .changeset/yellow-melons-decide.md
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/due-badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  __docs__/wonder-blocks-icon/custom-icon-components.stories.tsx
  __docs__/wonder-blocks-icon/icon.stories.tsx
  package.json
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/src/components/due-badge.tsx
  packages/wonder-blocks-badge/src/components/gem-badge.tsx
  packages/wonder-blocks-badge/src/components/status-badge.tsx
  packages/wonder-blocks-badge/src/components/streak-badge.tsx
  packages/wonder-blocks-icon/src/components/custom-icon-components/gem-icon.tsx
  packages/wonder-blocks-icon/src/components/custom-icon-components/streak-icon.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-tokens/src/tokens/color.ts
  pnpm-lock.yaml
Labels: olc-5.0.bf088

#2639 Badge text truncation
  .changeset/tall-buttons-explode.md
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/due-badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  packages/wonder-blocks-badge/src/components/__tests__/badge-types.test.tsx
  packages/wonder-blocks-badge/src/components/__tests__/badge.test.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-badge/src/types.ts
  packages/wonder-blocks-pill/src/components/pill.tsx
Labels: olc-5.0.b3e8b

#2636 [WB-1975] Add ActivityButton component
  .changeset/six-geckos-vanish.md
  __docs__/wonder-blocks-button/_overview_.mdx
  __docs__/wonder-blocks-button/activity-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/activity-button.argtypes.ts
  __docs__/wonder-blocks-button/activity-button.stories.tsx
  __docs__/wonder-blocks-button/button-shared.argtypes.ts
  __docs__/wonder-blocks-button/button.argtypes.ts
  packages/wonder-blocks-button/src/components/__tests__/button-types.test.tsx
  packages/wonder-blocks-button/src/components/activity-button.tsx
  packages/wonder-blocks-button/src/index.ts
  packages/wonder-blocks-button/src/util/button.types.ts
Labels: olc-5.0.b3e8b

#2652 Fix other image links in docs
  .changeset/red-bikes-divide.md
  __docs__/wonder-blocks-accordion/accordion.stories.tsx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/due-badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  __docs__/wonder-blocks-cell/compact-cell.argtypes.tsx
  __docs__/wonder-blocks-popover/popover-content.argtypes.tsx
  __docs__/wonder-blocks-popover/popover.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
Labels: olc-5.0.23186

#2645 Set up snapshots for Banner
  .changeset/neat-panthers-juggle.md
  __docs__/components/text-for-testing.ts
  __docs__/wonder-blocks-banner/banner-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-banner/banner.stories.tsx
Labels: olc-5.0.23186

#2653 Set up banner tokens structure and update styles
  .changeset/lazy-rice-cheat.md
  packages/wonder-blocks-banner/src/components/banner.tsx
Labels: olc-5.0.23186

#2644 [WB-1958.2] Add theming support to Cell
  .changeset/cool-parents-grow.md
  .changeset/late-days-join.md
  packages/wonder-blocks-cell/package.json
  packages/wonder-blocks-cell/src/components/__tests__/compact-cell.test.tsx
  packages/wonder-blocks-cell/src/components/__tests__/detail-cell.test.tsx
  packages/wonder-blocks-cell/src/components/compact-cell.tsx
  packages/wonder-blocks-cell/src/components/detail-cell.tsx
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
  packages/wonder-blocks-cell/src/components/internal/common.ts
  packages/wonder-blocks-cell/src/theme/default.ts
  packages/wonder-blocks-cell/src/theme/index.ts
  packages/wonder-blocks-cell/src/util/types.ts
  packages/wonder-blocks-cell/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.23186

#2655 Switch: Add support for Thunderblocks theming
  .changeset/real-kids-turn.md
  packages/wonder-blocks-switch/package.json
  packages/wonder-blocks-switch/src/components/switch.tsx
  packages/wonder-blocks-switch/src/theme/default.ts
  packages/wonder-blocks-switch/src/theme/index.ts
  packages/wonder-blocks-switch/src/theme/thunderblocks.ts
  packages/wonder-blocks-switch/src/themes/default.ts
  packages/wonder-blocks-switch/src/themes/themed-switch.tsx
  packages/wonder-blocks-tokens/src/theme/primitive/border.ts
Labels: olc-5.0.23186

#2656 Add thunderblocks theme to Banner
  .changeset/beige-buses-tan.md
  .changeset/healthy-boats-sniff.md
  __docs__/wonder-blocks-banner/banner-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-banner/banner.argtypes.ts
  __docs__/wonder-blocks-banner/banner.stories.tsx
  packages/wonder-blocks-banner/package.json
  packages/wonder-blocks-banner/src/components/banner.tsx
  packages/wonder-blocks-banner/src/theme/default.ts
  packages/wonder-blocks-banner/src/theme/index.ts
  packages/wonder-blocks-banner/src/theme/thunderblocks.ts
Labels: olc-5.0.23186

#2663 Add `styles` prop to `Banner` so that the `root` element can be styled
  .changeset/green-grapes-call.md
  __docs__/wonder-blocks-banner/banner.stories.tsx
  packages/wonder-blocks-banner/src/components/banner.tsx
Labels: olc-5.0.5673f

#2668 docs(changeset): Add tokens for themable Switch component
  .changeset/twelve-tomatoes-serve.md
Labels: olc-5.0.373be

#2661 [WB-1959.3] Cell layout refactor
  .changeset/chatty-moons-press.md
  .changeset/neat-lizards-teach.md
  .changeset/tame-eels-allow.md
  .changeset/twenty-eagles-cough.md
  __docs__/wonder-blocks-cell/compact-cell.argtypes.tsx
  __docs__/wonder-blocks-cell/detail-cell.stories.tsx
  packages/wonder-blocks-cell/package.json
  packages/wonder-blocks-cell/src/components/internal/__tests__/cell-core.test.tsx
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
  packages/wonder-blocks-cell/src/theme/default.ts
  packages/wonder-blocks-cell/src/theme/thunderblocks.ts
  packages/wonder-blocks-cell/src/util/types.ts
  packages/wonder-blocks-cell/tsconfig-build.json
  packages/wonder-blocks-dropdown/src/components/action-item.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  pnpm-lock.yaml
Labels: olc-5.0.e0c03

#2667 [🔥AUDIT🔥] Tokens: Move some TB colors out of OG primitives
  .changeset/happy-bears-wave.md
  __docs__/foundations-color.mdx
  __docs__/wonder-blocks-tokens/tokens-color.mdx
  packages/wonder-blocks-tokens/src/index.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-tokens/src/tokens/color.ts
Labels: audit, olc-5.0.5673f

#2670 [WB-1982] Add learning category to semanticColor tokens
  .changeset/brown-lions-share.md
  .changeset/pink-peaches-flow.md
  .changeset/wild-gorillas-cheer.md
  __docs__/foundations-color.mdx
  packages/wonder-blocks-badge/src/components/due-badge.tsx
  packages/wonder-blocks-badge/src/components/gem-badge.tsx
  packages/wonder-blocks-badge/src/components/streak-badge.tsx
  packages/wonder-blocks-icon/src/components/custom-icon-components/gem-icon.tsx
  packages/wonder-blocks-icon/src/components/custom-icon-components/streak-icon.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/internal/primitive-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.0171b

#2671 [FIX] Tokens: Adding input category to TB theme
  .changeset/calm-games-laugh.md
  .changeset/ninety-pigs-hunt.md
  __docs__/foundations-color.mdx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.0171b

#2666 Update styling of BodyText and Heading components to allow overrides
  .changeset/chatty-bees-explain.md
  __docs__/wonder-blocks-typography/body-text.stories.tsx
  __docs__/wonder-blocks-typography/heading.stories.tsx
  packages/wonder-blocks-typography/src/components/body-text.tsx
  packages/wonder-blocks-typography/src/components/heading.tsx
  packages/wonder-blocks-typography/src/util/styles.ts
Labels: olc-5.0.5673f

#2672 Form field theming set up
  .changeset/eleven-pianos-chew.md
  .changeset/flat-needles-sort.md
  .changeset/tiny-bottles-beam.md
  __docs__/components/scenarios-layout.tsx
  __docs__/wonder-blocks-form/text-area-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/text-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
  __docs__/wonder-blocks-search-field/search-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-search-field/search-field-variants.stories.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
Labels: olc-5.0.bc0e4

#2676 [WB-1867.1] Modal setup: Remove Khanmigo theme from modal
  .changeset/fast-crabs-give.md
  __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
  packages/wonder-blocks-modal/package.json
  packages/wonder-blocks-modal/src/components/modal-backdrop.tsx
  packages/wonder-blocks-modal/src/components/modal-content.tsx
  packages/wonder-blocks-modal/src/components/modal-dialog.tsx
  packages/wonder-blocks-modal/src/components/modal-footer.tsx
  packages/wonder-blocks-modal/src/components/modal-header.tsx
  packages/wonder-blocks-modal/src/components/modal-panel.tsx
  packages/wonder-blocks-modal/src/theme/default.ts
  packages/wonder-blocks-modal/src/theme/index.ts
  packages/wonder-blocks-modal/src/themes/khanmigo.ts
  packages/wonder-blocks-modal/src/themes/themed-modal-dialog.tsx
  pnpm-lock.yaml
Labels: olc-5.0.0171b

#2677 [WB-1867.2] Remove `light` prop from Modal package.
  .changeset/large-avocados-thank.md
  __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
  __docs__/wonder-blocks-modal/modal-footer.stories.tsx
  __docs__/wonder-blocks-modal/modal-header.argtypes.tsx
  __docs__/wonder-blocks-modal/modal-header.stories.tsx
  __docs__/wonder-blocks-modal/modal-panel.argtypes.tsx
  __docs__/wonder-blocks-modal/modal-panel.stories.tsx
  __docs__/wonder-blocks-modal/one-pane-dialog.stories.tsx
  packages/wonder-blocks-modal/src/components/modal-header.tsx
  packages/wonder-blocks-modal/src/components/modal-panel.tsx
  packages/wonder-blocks-modal/src/theme/default.ts
Labels: olc-5.0.0171b

#2681 Fix variable font rendering in Firefox
  .changeset/tough-seahorses-type.md
  static/jakarta.css
Labels: olc-5.0.2e29f

#2674 Minor tweaks for Tabs stories
  .changeset/breezy-shrimps-teach.md
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-utils.tsx
Labels: olc-5.0.0171b

#2682 [🔥AUDIT🔥] Export modal css vars from the tokens package.
  .changeset/shaggy-trees-drive.md
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: audit, olc-5.0.7fd07

#2684 Thunderblocks theming for TextField, TextArea, LabeledField
  .changeset/giant-penguins-wash.md
  .changeset/mean-bobcats-relate.md
  .changeset/real-jeans-clean.md
  .changeset/tricky-lies-develop.md
  __docs__/wonder-blocks-labeled-field/labeled-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
  packages/wonder-blocks-dropdown/package.json
  packages/wonder-blocks-dropdown/tsconfig-build.json
  packages/wonder-blocks-form/package.json
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-form/src/theme/default.ts
  packages/wonder-blocks-form/src/theme/index.ts
  packages/wonder-blocks-form/src/theme/thunderblocks.ts
  packages/wonder-blocks-labeled-field/package.json
  packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
  packages/wonder-blocks-labeled-field/src/theme/default.ts
  packages/wonder-blocks-labeled-field/src/theme/index.ts
  packages/wonder-blocks-labeled-field/src/theme/thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  pnpm-lock.yaml
Labels: olc-5.0.7fd07

#2662 Add theming to Checkbox/Radio
  .changeset/dull-experts-deny.md
  .changeset/nice-toys-sparkle.md
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-form/checkbox-accessibility.stories.tsx
  __docs__/wonder-blocks-form/checkbox-group.stories.tsx
  __docs__/wonder-blocks-form/checkbox.stories.tsx
  __docs__/wonder-blocks-form/choice.stories.tsx
  __docs__/wonder-blocks-form/radio-group.stories.tsx
  __docs__/wonder-blocks-form/radio.stories.tsx
  packages/wonder-blocks-dropdown/package.json
  packages/wonder-blocks-form/package.json
  packages/wonder-blocks-form/src/components/__tests__/checkbox.test.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/checkbox-group.tsx
  packages/wonder-blocks-form/src/components/choice-internal.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/radio-group.tsx
  packages/wonder-blocks-form/src/theme/default.ts
  packages/wonder-blocks-form/src/theme/index.ts
  packages/wonder-blocks-form/src/theme/thunderblocks.ts
  packages/wonder-blocks-form/src/util/styles.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  pnpm-lock.yaml
Labels: olc-5.0.5673f

#2680 [WB-1868.3] Add ThunderBlocks theme to dropdown
  .changeset/flat-feet-taste.md
  .changeset/new-zoos-retire.md
  __docs__/wonder-blocks-dropdown/combobox.stories.tsx
  packages/wonder-blocks-dropdown/package.json
  packages/wonder-blocks-dropdown/src/components/action-item.tsx
  packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.tsx
  packages/wonder-blocks-dropdown/src/components/check.tsx
  packages/wonder-blocks-dropdown/src/components/checkbox.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
  packages/wonder-blocks-dropdown/src/components/listbox.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-dropdown/src/components/separator-item.tsx
  packages/wonder-blocks-dropdown/src/theme/default.ts
  packages/wonder-blocks-dropdown/src/theme/index.ts
  packages/wonder-blocks-dropdown/src/theme/thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
Labels: olc-5.0.2e29f

#2693 LabeledField: Show the error icon for TB theme
  .changeset/heavy-dolphins-lie.md
  .changeset/short-spoons-approve.md
  __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
  packages/wonder-blocks-labeled-field/src/components/labeled-field.tsx
  packages/wonder-blocks-labeled-field/src/theme/default.ts
  packages/wonder-blocks-labeled-field/src/theme/thunderblocks.ts
Labels: olc-5.0.7fd07

#2696 [🔥AUDIT🔥] Dropdown: Fix dropdown labels to use div/span
  .changeset/ninety-feet-guess.md
  packages/wonder-blocks-dropdown/src/components/action-item.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
Labels: audit, olc-5.0.bfebe

#2694 Feature branch pull-request from `reintroduce-checkradio` to `main`
  .changeset/dull-experts-deny.md
  .changeset/nice-toys-sparkle.md
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-form/checkbox-accessibility.stories.tsx
  __docs__/wonder-blocks-form/checkbox-group.stories.tsx
  __docs__/wonder-blocks-form/checkbox.stories.tsx
  __docs__/wonder-blocks-form/choice.stories.tsx
  __docs__/wonder-blocks-form/radio-group.stories.tsx
  __docs__/wonder-blocks-form/radio.stories.tsx
  packages/wonder-blocks-dropdown/package.json
  packages/wonder-blocks-form/package.json
  packages/wonder-blocks-form/src/components/__tests__/checkbox.test.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/checkbox-group.tsx
  packages/wonder-blocks-form/src/components/choice-internal.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/radio-group.tsx
  packages/wonder-blocks-form/src/theme/default.ts
  packages/wonder-blocks-form/src/theme/index.ts
  packages/wonder-blocks-form/src/theme/thunderblocks.ts
  packages/wonder-blocks-form/src/util/styles.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  pnpm-lock.yaml
Labels: integration-branch, feature-branch, olc-5.0.bfebe

#2698 Add testing sheets for Heading/BodyText
  .changeset/pretty-rings-fold.md
  __docs__/wonder-blocks-typography/body-text-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-typography/heading-testing-snapshots.stories.tsx
Labels: olc-5.0.bfebe
