Repository Khan/wonder-blocks, pull requests merged in 2025-04, with the labels that each got.

#2550 [Storybook] Add StateSheet component to include different pseudo-states in the same snapshot
  .changeset/big-bats-dress.md
  __docs__/components/all-variants.tsx
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-dropdown/action-item-variants.stories.tsx
  __docs__/wonder-blocks-dropdown/option-item-variants.stories.tsx
  __docs__/wonder-blocks-form/checkbox-variants.stories.tsx
  __docs__/wonder-blocks-form/radio-variants.stories.tsx
  __docs__/wonder-blocks-icon-button/icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/icon-button-variants.stories.tsx
  __docs__/wonder-blocks-link/link-variants.stories.tsx
  __docs__/wonder-blocks-pill/pill-variants.stories.tsx
  __docs__/wonder-blocks-switch/switch-variants.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item-variants.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-variants.stories.tsx
Labels: olc-4.0.a6c9f

#2551 [WB-1922.1] Reconcile `border.radius` tokens to support TB
  .changeset/cold-colts-push.md
  .changeset/four-carrots-return.md
  .changeset/long-boxes-smell.md
  .changeset/quick-teachers-remain.md
  .changeset/slimy-planes-cross.md
  .changeset/stale-otters-sneeze.md
  __docs__/components/color.tsx
  __docs__/wonder-blocks-accordion/accordion-section.stories.tsx
  __docs__/wonder-blocks-cell/detail-cell.stories.tsx
  __docs__/wonder-blocks-core/add-style.mdx
  __docs__/wonder-blocks-core/add-style.stories.tsx
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  __docs__/wonder-blocks-link/link-variants.stories.tsx
  __docs__/wonder-blocks-switch/switch-variants.stories.tsx
  __docs__/wonder-blocks-theming/theme-examples.tsx
  __docs__/wonder-blocks-tokens/tokens-border.mdx
  packages/wonder-blocks-accordion/src/components/__tests__/accordion-section.test.tsx
  packages/wonder-blocks-accordion/src/components/__tests__/accordion.test.tsx
  packages/wonder-blocks-accordion/src/components/accordion-section.tsx
  packages/wonder-blocks-announcer/package.json
  packages/wonder-blocks-banner/src/components/banner.tsx
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-button/src/themes/khanmigo.ts
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
  packages/wonder-blocks-dropdown/src/components/action-item.tsx
  packages/wonder-blocks-dropdown/src/components/action-menu-opener-core.tsx
  packages/wonder-blocks-dropdown/src/components/checkbox.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
  packages/wonder-blocks-dropdown/src/components/option-item.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-icon-button/src/themes/default.ts
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-modal/src/themes/default.ts
  packages/wonder-blocks-pill/src/components/__tests__/pill.test.tsx
  packages/wonder-blocks-pill/src/components/pill.tsx
  packages/wonder-blocks-popover/src/components/popover-content-core.tsx
  packages/wonder-blocks-search-field/src/components/search-field.tsx
  packages/wonder-blocks-styles/src/styles/action-styles.ts
  packages/wonder-blocks-switch/src/themes/default.ts
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tokens/src/tokens/border.ts
  packages/wonder-blocks-tokens/src/tokens/sizing.ts
  packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
  pnpm-lock.yaml
Labels: olc-5.0.fb2b9

#2552 IconButton: Fix primary border on hover+focus and press+focus
  .changeset/rich-dingos-wink.md
  .changeset/violet-colts-burn.md
  packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
  packages/wonder-blocks-styles/src/styles/action-styles.ts
Labels: olc-5.0.fb2b9

#2554 [WB-1922.2] Reconcile border.width tokens to support TB
  .changeset/cool-pianos-rhyme.md
  .changeset/five-files-compare.md
  __docs__/components/all-variants.tsx
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  __docs__/wonder-blocks-icon/phosphor-icon.stories.tsx
  __docs__/wonder-blocks-modal/modal-panel.stories.tsx
  __docs__/wonder-blocks-styles/action-styles-variants.stories.tsx
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-button/src/themes/khanmigo.ts
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
  packages/wonder-blocks-clickable/src/components/clickable.tsx
  packages/wonder-blocks-dropdown/src/components/checkbox.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-form/src/components/checkbox-core.tsx
  packages/wonder-blocks-form/src/components/radio-core.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
  packages/wonder-blocks-form/src/components/text-field.tsx
  packages/wonder-blocks-icon-button/src/components/icon-button-core.tsx
  packages/wonder-blocks-icon-button/src/themes/default.ts
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-styles/src/styles/focus-styles.ts
  packages/wonder-blocks-tokens/src/tokens/border.ts
Labels: olc-5.0.fb2b9

#2545 Tabs: Styling
  .changeset/dirty-pens-share.md
  __docs__/components/placeholder.tsx
  __docs__/wonder-blocks-tabs/tab-variants.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-variants.stories.tsx
  __docs__/wonder-blocks-tabs/tabs.accessibility.mdx
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
  packages/wonder-blocks-tabs/src/components/tab-panel.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
  packages/wonder-blocks-tabs/src/components/tablist.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
  packages/wonder-blocks-tabs/src/hooks/use-tab-indicator.ts
  packages/wonder-blocks-tabs/tsconfig-build.json
Labels: olc-4.0.628d3

#2557 [WB-1644.1] Modify ThemeSwitcher to use a data-wb-theme attribute for theming
  .changeset/slimy-meals-tickle.md
  .changeset/yellow-lies-sort.md
  .storybook/main.ts
  .storybook/preview.tsx
  __docs__/components/color.tsx
  __docs__/components/token-table.tsx
  __docs__/components/tokens-util.ts
  __docs__/wonder-blocks-theming/theme-switcher.mdx
  __docs__/wonder-blocks-theming/theme-switcher.stories.tsx
  __docs__/wonder-blocks-tokens/tokens-semantic-color.mdx
  package.json
  packages/wonder-blocks-theming/src/components/theme-switcher.tsx
  packages/wonder-blocks-theming/src/index.ts
  packages/wonder-blocks-theming/src/utils/constants.ts
  packages/wonder-blocks-tokens/src/build/generate-css-variables.ts
  pnpm-lock.yaml
  vite.config.ts
Labels: olc-5.0.fb2b9

#2556 [WB-1926] Switch: Remove khanmigo theme, style updates
  .changeset/flat-bottles-flash.md
  __docs__/components/all-variants.tsx
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-switch/switch-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-switch/switch-variants.stories.tsx
  __docs__/wonder-blocks-switch/switch.stories.tsx
  packages/wonder-blocks-switch/package.json
  packages/wonder-blocks-switch/src/components/switch.tsx
  packages/wonder-blocks-switch/src/themes/default.ts
  packages/wonder-blocks-switch/src/themes/khanmigo.ts
  packages/wonder-blocks-switch/src/themes/themed-switch.tsx
  packages/wonder-blocks-switch/tsconfig-build.json
  pnpm-lock.yaml
Labels: olc-5.0.fb2b9

#2549 Replaced moment.js with Temporal polyfill
  .changeset/tricky-lizards-lie.md
  .github/workflows/chromatic-build.yml
  package.json
  packages/wonder-blocks-birthday-picker/package.json
  packages/wonder-blocks-birthday-picker/src/components/__tests__/birthday-picker.test.tsx
  packages/wonder-blocks-birthday-picker/src/components/birthday-picker.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: olc-5.0.fb2b9

#2564 [🔥AUDIT🔥] Tokens: Export TS types correctly in package.json so consumers can use them correctly
  .changeset/odd-turkeys-train.md
  packages/wonder-blocks-tokens/package.json
Labels: audit, olc-5.0.fb2b9

#2565 Deprecate fixtures framework
  .changeset/clever-kids-talk.md
  packages/wonder-blocks-testing-core/src/fixtures/fixtures.basic.stories.tsx
  packages/wonder-blocks-testing-core/src/fixtures/fixtures.defaultwrapper.stories.tsx
  packages/wonder-blocks-testing-core/src/fixtures/fixtures.tsx
  packages/wonder-blocks-testing-core/src/fixtures/types.ts
Labels: olc-5.0.407da

#2541 This is a feature-branch pull-request from `feature/css-vars` to `main`
  .changeset/clean-ravens-happen.md
  .changeset/gold-peaches-guess.md
  .changeset/heavy-islands-tan.md
  .changeset/odd-turkeys-train.md
  .changeset/silver-pumas-marry.md
  .changeset/slimy-meals-tickle.md
  .changeset/ten-gorillas-invent.md
  .changeset/tidy-humans-fail.md
  .changeset/yellow-lies-sort.md
  .storybook/main.ts
  .storybook/preview.tsx
  __docs__/components/color.tsx
  __docs__/components/token-table.tsx
  __docs__/components/tokens-util.ts
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-theming/theme-switcher.mdx
  __docs__/wonder-blocks-theming/theme-switcher.stories.tsx
  __docs__/wonder-blocks-tokens/tokens-border.mdx
  __docs__/wonder-blocks-tokens/tokens-semantic-color.mdx
  __docs__/wonder-blocks-tokens/tokens-sizing.mdx
  package.json
  packages/wonder-blocks-dropdown/src/components/select-opener.tsx
  packages/wonder-blocks-pill/src/components/pill.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-theming/src/components/theme-switcher.tsx
  packages/wonder-blocks-theming/src/index.ts
  packages/wonder-blocks-theming/src/utils/__tests__/merge-theme.test.ts
  packages/wonder-blocks-theming/src/utils/constants.ts
  packages/wonder-blocks-theming/tsconfig-build.json
  packages/wonder-blocks-tokens/package.json
  packages/wonder-blocks-tokens/src/build/generate-css-variables.ts
  packages/wonder-blocks-tokens/src/index.ts
  packages/wonder-blocks-tokens/src/internal/__test__/generate-tokens.test.ts
  packages/wonder-blocks-tokens/src/internal/__test__/map-values-to-css-vars.test.ts
  packages/wonder-blocks-tokens/src/internal/generate-tokens.ts
  packages/wonder-blocks-tokens/src/internal/map-values-to-css-vars.ts
  packages/wonder-blocks-tokens/src/theme/default.ts
  packages/wonder-blocks-tokens/src/theme/primitive/border.ts
  packages/wonder-blocks-tokens/src/theme/primitive/sizing.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-tokens/src/tokens/theme.ts
  packages/wonder-blocks-tokens/src/util/constants.ts
  packages/wonder-blocks-tokens/src/util/types.ts
  packages/wonder-blocks-tokens/tsconfig-build.json
  pnpm-lock.yaml
  types/assets.d.ts
  vite.config.ts
Labels: olc-4.0.a6c9f

#2568 Use StateSheet for tabs package stories & address snapshot flakiness
  .changeset/eighty-rockets-repeat.md
  .changeset/new-swans-hug.md
  .changeset/polite-spies-press.md
  __docs__/components/all-variants.tsx
  __docs__/components/state-sheet.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-utils.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-tabs/tab-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-utils.tsx
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tabs.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
  packages/wonder-blocks-tabs/src/components/tablist.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
  packages/wonder-blocks-tabs/src/hooks/use-tab-indicator.ts
Labels: olc-5.0.407da

#2563 [WB-1852.2] Remove Button.light variant, modify actionStyles to support Button instances
  .changeset/fluffy-donuts-drop.md
  .changeset/grumpy-seas-crash.md
  __docs__/wonder-blocks-button/button-variants.stories.tsx
  __docs__/wonder-blocks-button/button.argtypes.ts
  __docs__/wonder-blocks-button/button.stories.tsx
  __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
  __docs__/wonder-blocks-modal/modal-panel.stories.tsx
  __docs__/wonder-blocks-popover/popover-content.argtypes.tsx
  __docs__/wonder-blocks-styles/action-styles-variants.stories.tsx
  __docs__/wonder-blocks-styles/action-styles.stories.tsx
  __docs__/wonder-blocks-toolbar/toolbar.argtypes.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/themes/default.ts
  packages/wonder-blocks-styles/src/styles/action-styles.ts
Labels: olc-5.0.fb2b9

#2569 Tabs: Add `mountAllPanels` prop.
  .changeset/fair-ants-hunt.md
  __docs__/wonder-blocks-tabs/tabs.stories.tsx
  packages/wonder-blocks-tabs/src/components/__tests__/tabs.test.tsx
  packages/wonder-blocks-tabs/src/components/tabs.tsx
Labels: olc-5.0.407da
