Repository Khan/wonder-blocks, pull requests merged in 2025-08, with the labels that each got.

#2747 Add dir type to View for RLT support
  .changeset/empty-cars-pay.md
  .changeset/sixty-cobras-kneel.md
  __docs__/wonder-blocks-core/view.argtypes.ts
  __docs__/wonder-blocks-typography/typography.stories.tsx
  packages/wonder-blocks-core/src/util/types.ts
Labels: olc-5.0.b27e5

#2748 Add section to readme about building packages
  .changeset/wise-sloths-lay.md
  README.md
Labels: olc-5.0.b27e5

#2746 Stories: use theme modes constant
  .changeset/light-ties-train.md
  __docs__/components/copy-button.tsx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-badge/due-badge.stories.tsx
  __docs__/wonder-blocks-badge/status-badge.stories.tsx
  __docs__/wonder-blocks-banner/banner-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/activity-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-button/button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-cell/compact-cell-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-cell/detail-cell-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/action-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/multi-select-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/option-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/checkbox-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/radio-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/text-area-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/text-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/activity-icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/conversation-icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon-button/icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon/custom-icon-components.stories.tsx
  __docs__/wonder-blocks-icon/icon.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-labeled-field/labeled-field.stories.tsx
  __docs__/wonder-blocks-pill/pill-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-search-field/search-field-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-switch/switch-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tab-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/tabs-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tokens/__overview__.mdx
  __docs__/wonder-blocks-tokens/color.stories.tsx
  __docs__/wonder-blocks-typography/body-text-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-typography/body-text.stories.tsx
  __docs__/wonder-blocks-typography/heading-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-typography/heading.stories.tsx
  __docs__/wonder-blocks-typography/typography.stories.tsx
Labels: olc-5.0.b27e5

#2743 Add theming to Link, use BodyText in Button
  .changeset/forty-icons-wait.md
  .changeset/lazy-dolphins-stare.md
  .changeset/red-numbers-fold.md
  .storybook/preview-head.html
  __docs__/wonder-blocks-link/link-testing-snapshots.stories.tsx
  packages/wonder-blocks-breadcrumbs/src/components/breadcrumbs-item.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-link/package.json
  packages/wonder-blocks-link/src/components/link-core.tsx
  packages/wonder-blocks-link/src/theme/default.ts
  packages/wonder-blocks-link/src/theme/index.ts
  packages/wonder-blocks-link/src/theme/thunderblocks.ts
  packages/wonder-blocks-link/tsconfig-build.json
  packages/wonder-blocks-tokens/src/theme/primitive/border.ts
  packages/wonder-blocks-tokens/src/theme/primitive/font.ts
  pnpm-lock.yaml
Labels: olc-5.0.e3fd9

#2754 Update Tab and NavigationTabItem font color
  .changeset/tender-items-move.md
  __docs__/wonder-blocks-tabs/navigation-tab-item-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tab-item.stories.tsx
  packages/wonder-blocks-tabs/src/components/navigation-tab-item.tsx
  packages/wonder-blocks-tabs/src/components/tab.tsx
Labels: olc-5.0.b27e5

#2744 Create new Modal DrawerLauncher component
  .changeset/empty-maps-watch.md
  .changeset/hot-birds-scream.md
  .storybook/preview.tsx
  __docs__/wonder-blocks-modal/drawer-dialog.argtypes.ts
  __docs__/wonder-blocks-modal/drawer-dialog.stories.tsx
  __docs__/wonder-blocks-modal/drawer-launcher-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-modal/drawer-launcher.argtypes.ts
  __docs__/wonder-blocks-modal/drawer-launcher.stories.tsx
  __docs__/wonder-blocks-modal/flexible-dialog.argtypes.ts
  __docs__/wonder-blocks-modal/flexible-dialog.stories.tsx
  packages/wonder-blocks-modal/src/components/__tests__/drawer-backdrop.test.tsx
  packages/wonder-blocks-modal/src/components/__tests__/drawer-dialog.test.tsx
  packages/wonder-blocks-modal/src/components/__tests__/drawer-launcher.test.tsx
  packages/wonder-blocks-modal/src/components/__tests__/flexible-panel.test.tsx
  packages/wonder-blocks-modal/src/components/__tests__/modal-launcher.test.tsx
  packages/wonder-blocks-modal/src/components/drawer-backdrop.tsx
  packages/wonder-blocks-modal/src/components/drawer-dialog.tsx
  packages/wonder-blocks-modal/src/components/drawer-launcher.tsx
  packages/wonder-blocks-modal/src/components/flexible-dialog.tsx
  packages/wonder-blocks-modal/src/components/flexible-panel.tsx
  packages/wonder-blocks-modal/src/components/modal-panel.tsx
  packages/wonder-blocks-modal/src/hooks/__tests__/use-direction-detection.test.tsx
  packages/wonder-blocks-modal/src/hooks/use-direction-detection.ts
  packages/wonder-blocks-modal/src/index.ts
  packages/wonder-blocks-modal/src/util/drawer-context.ts
  packages/wonder-blocks-modal/src/util/types.ts
  static/sb-styles/preview.css
Labels: olc-5.0.e3fd9

#2765 Add programmatic focus to Button
  .changeset/busy-seals-strive.md
  __docs__/wonder-blocks-button/activity-button.stories.tsx
  __docs__/wonder-blocks-button/button.stories.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
Labels: olc-5.0.e7698

#2766 Use new background tokens in WB components
  .changeset/flat-pumpkins-provide.md
  .storybook/preview.tsx
  __docs__/components/code.tsx
  __docs__/components/color.tsx
  __docs__/components/placeholder.tsx
  __docs__/wonder-blocks-badge/badge-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-badge/badge.stories.tsx
  __docs__/wonder-blocks-cell/compact-cell.stories.tsx
  __docs__/wonder-blocks-cell/detail-cell.stories.tsx
  __docs__/wonder-blocks-clickable/clickable.stories.tsx
  __docs__/wonder-blocks-dropdown/action-item.stories.tsx
  __docs__/wonder-blocks-dropdown/action-menu.stories.tsx
  __docs__/wonder-blocks-dropdown/combobox.stories.tsx
  __docs__/wonder-blocks-dropdown/listbox.stories.tsx
  __docs__/wonder-blocks-dropdown/option-item.stories.tsx
  __docs__/wonder-blocks-icon-button/activity-icon-button-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-icon/custom-icon-components.stories.tsx
  __docs__/wonder-blocks-link/link-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-link/link.stories.tsx
  __docs__/wonder-blocks-modal/modal-dialog.stories.tsx
  __docs__/wonder-blocks-pill/pill.stories.tsx
  __docs__/wonder-blocks-styles/action-styles-variants.stories.tsx
  __docs__/wonder-blocks-styles/focus-styles.stories.tsx
  __docs__/wonder-blocks-tabs/navigation-tabs.stories.tsx
  __docs__/wonder-blocks-tokens/semantic-color.stories.tsx
  packages/wonder-blocks-accordion/src/components/accordion-section.tsx
  packages/wonder-blocks-badge/src/components/badge.tsx
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
  packages/wonder-blocks-dropdown/src/components/combobox.tsx
  packages/wonder-blocks-dropdown/src/components/dropdown-core.tsx
  packages/wonder-blocks-dropdown/src/components/listbox.tsx
  packages/wonder-blocks-form/src/util/styles.ts
  packages/wonder-blocks-modal/src/components/drawer-backdrop.tsx
  packages/wonder-blocks-modal/src/components/flexible-panel.tsx
  packages/wonder-blocks-modal/src/components/modal-backdrop.tsx
  packages/wonder-blocks-modal/src/components/modal-panel.tsx
  packages/wonder-blocks-popover/src/components/popover-content-core.tsx
  packages/wonder-blocks-styles/src/styles/action-styles.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color-thunderblocks.ts
  packages/wonder-blocks-tokens/src/theme/semantic/semantic-color.ts
  packages/wonder-blocks-toolbar/src/components/toolbar.tsx
  packages/wonder-blocks-tooltip/src/components/tooltip-bubble.tsx
Labels: olc-5.0.11e3f

#2763 Add onMouseDown / onMouseDown / onMouseLeave to `ActivityButton` and `Button`
  .changeset/dirty-toys-dance.md
  __docs__/wonder-blocks-button/activity-button.stories.tsx
  __docs__/wonder-blocks-button/button-shared.argtypes.ts
  __docs__/wonder-blocks-button/button.stories.tsx
  packages/wonder-blocks-button/src/components/__tests__/activity-button.test.tsx
  packages/wonder-blocks-button/src/components/__tests__/button.test.tsx
  packages/wonder-blocks-button/src/components/activity-button.tsx
  packages/wonder-blocks-button/src/components/button-core.tsx
  packages/wonder-blocks-button/src/components/button.tsx
  packages/wonder-blocks-button/src/util/button.types.ts
  packages/wonder-blocks-clickable/src/components/__tests__/clickable-behavior.test.tsx
  packages/wonder-blocks-clickable/src/components/clickable-behavior.ts
  packages/wonder-blocks-clickable/src/components/clickable.tsx
Labels: olc-5.0.11e3f
