Repository Khan/wonder-blocks, pull requests merged in 2025-10, with the labels that each got.

#2800 TextArea: Support dynamic content sizing
  .changeset/spotty-balloons-swim.md
  __docs__/components/text-for-testing.ts
  __docs__/wonder-blocks-form/text-area-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-form/text-area.stories.tsx
  packages/wonder-blocks-form/src/components/__tests__/text-area.test.tsx
  packages/wonder-blocks-form/src/components/text-area.tsx
Labels: olc-5.0.2f60c

#2810 WB-2067: Prevent premature announcements in SingleSelect and MultiSelect
  .changeset/fluffy-glasses-rest.md
  __docs__/wonder-blocks-dropdown/multi-select.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  packages/wonder-blocks-dropdown/src/components/__tests__/multi-select.test.tsx
  packages/wonder-blocks-dropdown/src/components/__tests__/single-select.test.tsx
  packages/wonder-blocks-dropdown/src/components/multi-select.tsx
  packages/wonder-blocks-dropdown/src/components/single-select.tsx
Labels: olc-5.0.853e0

#2811 FlexibleDialog: Fix positioning at middle breakpoint size
  .changeset/brave-books-attend.md
  packages/wonder-blocks-modal/src/components/flexible-dialog.tsx
Labels: olc-5.0.853e0

#2799 Create initial Card component
  .changeset/moody-rivers-roll.md
  __docs__/wonder-blocks-card/accessibility.mdx
  __docs__/wonder-blocks-card/card.argtypes.tsx
  __docs__/wonder-blocks-card/card.stories.tsx
  packages/wonder-blocks-card/CHANGELOG.md
  packages/wonder-blocks-card/package.json
  packages/wonder-blocks-card/src/__tests__/components/card.test.tsx
  packages/wonder-blocks-card/src/__tests__/components/card.typestest.tsx
  packages/wonder-blocks-card/src/__tests__/components/dismiss-button.test.tsx
  packages/wonder-blocks-card/src/components/card.tsx
  packages/wonder-blocks-card/src/components/dismiss-button.tsx
  packages/wonder-blocks-card/src/index.ts
  packages/wonder-blocks-card/tsconfig-build.json
  packages/wonder-blocks-card/types
  pnpm-lock.yaml
Labels: olc-5.0.0b737

#2808 [WB-2101] Fix left-aligned dropdown components to be right-aligned
  .changeset/fifty-bottles-happen.md
  .changeset/happy-trains-swim.md
  __docs__/components/scenarios-layout.tsx
  __docs__/wonder-blocks-cell/compact-cell-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-cell/detail-cell-testing-snapshots.stories.tsx
  __docs__/wonder-blocks-dropdown/single-select.stories.tsx
  packages/wonder-blocks-cell/src/components/internal/cell-core.tsx
Labels: olc-5.0.853e0

#2814 Miscellaneous docs updates in Wonder Blocks
  .changeset/purple-buckets-travel.md
  __docs__/wonder-blocks-dropdown/_overview_.mdx
  __docs__/wonder-blocks-modal/_overview_.mdx
  __docs__/wonder-blocks-modal/flexible-dialog.stories.tsx
  __docs__/wonder-blocks-typography/body-text.stories.tsx
Labels: olc-5.0.853e0
